name:CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
       uses: actions/checkout@v4

      -name: Print environment info
       run:  |
         whoami
         pwd
         date

      -name: Create and read a file
      run: |
        echo "build ran at $(data)" > build-log.txt
        cat build-log.tx
